name: vbs_sos
description: "VBS-SOS is a mobile app to send sos design for companies"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  circular_bottom_navigation: ^2.3.0
  intl: ^0.18.0
  http: ^1.1.2
  restart_app: ^1.2.1
  pin_code_text_field: ^1.8.0
  page_transition: ^2.1.0
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  awesome_dialog: ^3.2.0
  latlong2: ^0.9.0
  permission_handler: ^11.2.0
  flutter_local_notifications: ^9.0.0
  app_settings: ^5.0.2
  webview_flutter: ^2.0.14
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.10
  flutter_inset_box_shadow: ^1.0.8
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  sqflite: ^2.3.2
  fluttertoast: ^8.2.4
  path: ^1.8.3
  flutter_spinkit: ^5.2.0
  icons_plus: ^5.0.0

icons_launcher:
  image_path: "assets/images/ic_launcher.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
